-- ESP32-C3 OLED control plane. All browser/device traffic goes through the
-- same-origin Next.js API; these tables and the private bucket are server-only.

create table if not exists public.esp32_devices (
  id uuid primary key default gen_random_uuid(),
  device_uid text not null unique check (char_length(device_uid) between 8 and 80),
  token_hash text not null check (char_length(token_hash) = 64),
  owner_auth_user_id uuid references auth.users(id) on delete set null,
  name text not null default 'Мой OLED' check (char_length(name) between 1 and 48),
  firmware_version text,
  hardware jsonb not null default '{}'::jsonb,
  manifest jsonb not null default '[]'::jsonb,
  active_slot smallint check (active_slot between 0 and 9),
  flash_size bigint not null default 0 check (flash_size >= 0),
  fs_total bigint not null default 0 check (fs_total >= 0),
  fs_used bigint not null default 0 check (fs_used >= 0 and fs_used <= fs_total),
  brightness smallint not null default 128 check (brightness between 0 and 255),
  speed_multiplier numeric(4,2) not null default 1 check (speed_multiplier between 0.25 and 4),
  last_seen_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists esp32_devices_owner_idx
  on public.esp32_devices(owner_auth_user_id) where owner_auth_user_id is not null and revoked_at is null;

create table if not exists public.esp32_pairing_challenges (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.esp32_devices(id) on delete cascade,
  pin_hash text not null check (char_length(pin_hash) = 64),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists esp32_pairing_active_idx
  on public.esp32_pairing_challenges(pin_hash, expires_at)
  where consumed_at is null;

create table if not exists public.esp32_pairing_attempts (
  rate_key_hash text primary key check (char_length(rate_key_hash) = 64),
  window_started_at timestamptz not null default now(),
  attempts integer not null default 0 check (attempts >= 0),
  blocked_until timestamptz
);

create table if not exists public.esp32_device_commands (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.esp32_devices(id) on delete cascade,
  owner_auth_user_id uuid not null references auth.users(id) on delete cascade,
  command_type text not null check (command_type in (
    'upload_asset', 'delete_asset', 'rename_asset', 'set_active',
    'set_settings', 'request_manifest', 'reboot', 'reset_wifi'
  )),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued', 'in_progress', 'succeeded', 'failed', 'cancelled')),
  idempotency_key text not null,
  attempts integer not null default 0 check (attempts between 0 and 5),
  available_at timestamptz not null default now(),
  claimed_at timestamptz,
  acknowledged_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (device_id, idempotency_key)
);

create index if not exists esp32_commands_device_queue_idx
  on public.esp32_device_commands(device_id, status, available_at, created_at);
create index if not exists esp32_commands_owner_idx
  on public.esp32_device_commands(owner_auth_user_id, created_at desc);

create table if not exists public.esp32_device_events (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.esp32_devices(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 1 and 64),
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists esp32_events_device_idx
  on public.esp32_device_events(device_id, occurred_at desc);

create or replace function public.esp32_touch_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists esp32_devices_touch on public.esp32_devices;
create trigger esp32_devices_touch before update on public.esp32_devices
for each row execute function public.esp32_touch_updated_at();
drop trigger if exists esp32_commands_touch on public.esp32_device_commands;
create trigger esp32_commands_touch before update on public.esp32_device_commands
for each row execute function public.esp32_touch_updated_at();

create or replace function public.esp32_claim_device(
  p_pin_hash text,
  p_owner uuid,
  p_rate_key_hash text,
  p_name text default 'Мой OLED'
) returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_rate public.esp32_pairing_attempts%rowtype;
  v_candidate record;
  v_device_id uuid;
  v_count integer := 0;
begin
  insert into public.esp32_pairing_attempts(rate_key_hash, attempts)
  values (p_rate_key_hash, 0)
  on conflict (rate_key_hash) do nothing;

  select * into v_rate
  from public.esp32_pairing_attempts
  where rate_key_hash = p_rate_key_hash
  for update;

  if v_rate.blocked_until is not null and v_rate.blocked_until > now() then
    raise exception 'RATE_LIMITED';
  end if;

  if v_rate.window_started_at < now() - interval '10 minutes' then
    update public.esp32_pairing_attempts
      set window_started_at = now(), attempts = 1, blocked_until = null
      where rate_key_hash = p_rate_key_hash;
  else
    update public.esp32_pairing_attempts
      set attempts = attempts + 1,
          blocked_until = case when attempts + 1 > 5 then now() + interval '15 minutes' else blocked_until end
      where rate_key_hash = p_rate_key_hash
      returning * into v_rate;
    if v_rate.attempts > 5 then raise exception 'RATE_LIMITED'; end if;
  end if;

  for v_candidate in
    select c.id as challenge_id, d.id as device_id
    from public.esp32_pairing_challenges c
    join public.esp32_devices d on d.id = c.device_id
    where c.pin_hash = p_pin_hash
      and c.consumed_at is null
      and c.expires_at > now()
      and d.owner_auth_user_id is null
      and d.revoked_at is null
      and d.last_seen_at > now() - interval '90 seconds'
    order by c.created_at desc
    limit 2
    for update of c, d
  loop
    v_count := v_count + 1;
    v_device_id := v_candidate.device_id;
  end loop;

  if v_count = 0 then raise exception 'PAIRING_NOT_FOUND'; end if;
  if v_count > 1 then raise exception 'PAIRING_AMBIGUOUS'; end if;

  update public.esp32_devices
    set owner_auth_user_id = p_owner,
        name = left(coalesce(nullif(trim(p_name), ''), 'Мой OLED'), 48)
    where id = v_device_id and owner_auth_user_id is null;
  if not found then raise exception 'DEVICE_ALREADY_CLAIMED'; end if;

  update public.esp32_pairing_challenges
    set consumed_at = now()
    where device_id = v_device_id and consumed_at is null;
  delete from public.esp32_pairing_attempts where rate_key_hash = p_rate_key_hash;
  return v_device_id;
end;
$$;

create or replace function public.esp32_claim_next_command(p_device_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_row public.esp32_device_commands%rowtype;
begin
  select * into v_row
  from public.esp32_device_commands
  where device_id = p_device_id
    and attempts < 5
    and available_at <= now()
    and (
      status = 'queued'
      or (status = 'in_progress' and claimed_at < now() - interval '30 seconds')
    )
  order by created_at
  limit 1
  for update skip locked;

  if v_row.id is null then return null; end if;

  update public.esp32_device_commands
    set status = 'in_progress', claimed_at = now(), attempts = attempts + 1
    where id = v_row.id
    returning * into v_row;
  return to_jsonb(v_row);
end;
$$;

alter table public.esp32_devices enable row level security;
alter table public.esp32_pairing_challenges enable row level security;
alter table public.esp32_pairing_attempts enable row level security;
alter table public.esp32_device_commands enable row level security;
alter table public.esp32_device_events enable row level security;

revoke all on table public.esp32_devices from anon, authenticated;
revoke all on table public.esp32_pairing_challenges from anon, authenticated;
revoke all on table public.esp32_pairing_attempts from anon, authenticated;
revoke all on table public.esp32_device_commands from anon, authenticated;
revoke all on table public.esp32_device_events from anon, authenticated;
grant all on table public.esp32_devices to service_role;
grant all on table public.esp32_pairing_challenges to service_role;
grant all on table public.esp32_pairing_attempts to service_role;
grant all on table public.esp32_device_commands to service_role;
grant all on table public.esp32_device_events to service_role;
grant usage, select on sequence public.esp32_device_events_id_seq to service_role;

revoke all on function public.esp32_claim_device(text, uuid, text, text) from public, anon, authenticated;
revoke all on function public.esp32_claim_next_command(uuid) from public, anon, authenticated;
grant execute on function public.esp32_claim_device(text, uuid, text, text) to service_role;
grant execute on function public.esp32_claim_next_command(uuid) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('esp32-oled-assets', 'esp32-oled-assets', false, 2097152, array['application/octet-stream'])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

